# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.api.domains_api import DomainsApi


class TestDomainsApi(unittest.TestCase):
    """DomainsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DomainsApi()

    def tearDown(self) -> None:
        pass

    def test_check_tenant_domain(self) -> None:
        """Test case for check_tenant_domain

        Check tenant domain verification
        """
        pass

    def test_create_tenant_domain(self) -> None:
        """Test case for create_tenant_domain

        Add tenant domain
        """
        pass

    def test_get_tenant_domain(self) -> None:
        """Test case for get_tenant_domain

        Get tenant domain details
        """
        pass

    def test_list_tenant_domains(self) -> None:
        """Test case for list_tenant_domains

        List tenant domains
        """
        pass


if __name__ == '__main__':
    unittest.main()
