# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.tenant_message_provider_meta import TenantMessageProviderMeta

class TestTenantMessageProviderMeta(unittest.TestCase):
    """TenantMessageProviderMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantMessageProviderMeta:
        """Test TenantMessageProviderMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantMessageProviderMeta`
        """
        model = TenantMessageProviderMeta()
        if include_optional:
            return TenantMessageProviderMeta(
                mail = { },
                send = { },
                delivery = { },
                provider_event_type = 'Send'
            )
        else:
            return TenantMessageProviderMeta(
        )
        """

    def testTenantMessageProviderMeta(self):
        """Test TenantMessageProviderMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
