# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.tenant_message_event_delivery import TenantMessageEventDelivery

class TestTenantMessageEventDelivery(unittest.TestCase):
    """TenantMessageEventDelivery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantMessageEventDelivery:
        """Test TenantMessageEventDelivery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantMessageEventDelivery`
        """
        model = TenantMessageEventDelivery()
        if include_optional:
            return TenantMessageEventDelivery(
                smtp_response = '250 2.6.0 <010b019ce6cb1552-32720d7c-a2cd-4716-a559-f587669ecacb-000000@eu-west-2.amazonses.com> ...',
                processing_time_millis = 1371,
                reporting_mta = 'd218-9.smtp-out.eu-west-2.amazonses.com',
                remote_mta_ip = '52.101.89.1',
                recipients = [developers@dependal.com],
                timestamp = '2026-03-13T10:43:16.269Z'
            )
        else:
            return TenantMessageEventDelivery(
        )
        """

    def testTenantMessageEventDelivery(self):
        """Test TenantMessageEventDelivery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
