# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.tenant_policies_accept_response import TenantPoliciesAcceptResponse

class TestTenantPoliciesAcceptResponse(unittest.TestCase):
    """TenantPoliciesAcceptResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantPoliciesAcceptResponse:
        """Test TenantPoliciesAcceptResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantPoliciesAcceptResponse`
        """
        model = TenantPoliciesAcceptResponse()
        if include_optional:
            return TenantPoliciesAcceptResponse(
                data = openapi_client.models.tenant_policies_accept.TenantPoliciesAccept(
                    ok = True, 
                    accepted_version = '2026-02-22', 
                    required_policy_version = '2026-02-22', )
            )
        else:
            return TenantPoliciesAcceptResponse(
                data = openapi_client.models.tenant_policies_accept.TenantPoliciesAccept(
                    ok = True, 
                    accepted_version = '2026-02-22', 
                    required_policy_version = '2026-02-22', ),
        )
        """

    def testTenantPoliciesAcceptResponse(self):
        """Test TenantPoliciesAcceptResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
