# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.message_status_response import MessageStatusResponse

class TestMessageStatusResponse(unittest.TestCase):
    """MessageStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageStatusResponse:
        """Test MessageStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageStatusResponse`
        """
        model = MessageStatusResponse()
        if include_optional:
            return MessageStatusResponse(
                data = openapi_client.models.message_status.MessageStatus(
                    message_id = '1a011c24-788e-4273-8c81-fd7d767bf0c0', 
                    status = 'ACCEPTED', 
                    reason = '', 
                    created_at = 1773398594, 
                    updated_at = 1773398596, 
                    to = 'developers@dependal.com', 
                    from = 'Dependal <noreply@dependal.com>', 
                    subject = 'Dependal test send', 
                    sending_message_id = '010b019ce6cb1552-32720d7c-a2cd-4716-a559-f587669ecacb-000000', )
            )
        else:
            return MessageStatusResponse(
                data = openapi_client.models.message_status.MessageStatus(
                    message_id = '1a011c24-788e-4273-8c81-fd7d767bf0c0', 
                    status = 'ACCEPTED', 
                    reason = '', 
                    created_at = 1773398594, 
                    updated_at = 1773398596, 
                    to = 'developers@dependal.com', 
                    from = 'Dependal <noreply@dependal.com>', 
                    subject = 'Dependal test send', 
                    sending_message_id = '010b019ce6cb1552-32720d7c-a2cd-4716-a559-f587669ecacb-000000', ),
        )
        """

    def testMessageStatusResponse(self):
        """Test MessageStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
