# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.tenant_domain_record import TenantDomainRecord

class TestTenantDomainRecord(unittest.TestCase):
    """TenantDomainRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantDomainRecord:
        """Test TenantDomainRecord
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantDomainRecord`
        """
        model = TenantDomainRecord()
        if include_optional:
            return TenantDomainRecord(
                type = 'CNAME',
                name = 'cieoxyt4oxhvpr5zmdeqxoxzqgs6umsu._domainkey.yourdomain.com',
                value = 'cieoxyt4oxhvpr5zmdeqxoxzqgs6umsu.dkim.amazonses.com'
            )
        else:
            return TenantDomainRecord(
                type = 'CNAME',
                name = 'cieoxyt4oxhvpr5zmdeqxoxzqgs6umsu._domainkey.yourdomain.com',
                value = 'cieoxyt4oxhvpr5zmdeqxoxzqgs6umsu.dkim.amazonses.com',
        )
        """

    def testTenantDomainRecord(self):
        """Test TenantDomainRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
