# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.tenant_domain_detail import TenantDomainDetail

class TestTenantDomainDetail(unittest.TestCase):
    """TenantDomainDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantDomainDetail:
        """Test TenantDomainDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantDomainDetail`
        """
        model = TenantDomainDetail()
        if include_optional:
            return TenantDomainDetail(
                domain = 'yourdomain.com',
                mail_from_domain = 'mail.yourdomain.com',
                status = 'PENDING',
                ses = openapi_client.models.tenant_domain_ses_status.TenantDomainSesStatus(
                    verification_status = 'PENDING', 
                    dkim_status = 'PENDING', ),
                records = [
                    openapi_client.models.tenant_domain_record.TenantDomainRecord(
                        type = 'CNAME', 
                        name = 'cieoxyt4oxhvpr5zmdeqxoxzqgs6umsu._domainkey.yourdomain.com', 
                        value = 'cieoxyt4oxhvpr5zmdeqxoxzqgs6umsu.dkim.amazonses.com', )
                    ]
            )
        else:
            return TenantDomainDetail(
                domain = 'yourdomain.com',
                mail_from_domain = 'mail.yourdomain.com',
                status = 'PENDING',
                ses = openapi_client.models.tenant_domain_ses_status.TenantDomainSesStatus(
                    verification_status = 'PENDING', 
                    dkim_status = 'PENDING', ),
                records = [
                    openapi_client.models.tenant_domain_record.TenantDomainRecord(
                        type = 'CNAME', 
                        name = 'cieoxyt4oxhvpr5zmdeqxoxzqgs6umsu._domainkey.yourdomain.com', 
                        value = 'cieoxyt4oxhvpr5zmdeqxoxzqgs6umsu.dkim.amazonses.com', )
                    ],
        )
        """

    def testTenantDomainDetail(self):
        """Test TenantDomainDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
