# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.tenant_domain_detail_response import TenantDomainDetailResponse

class TestTenantDomainDetailResponse(unittest.TestCase):
    """TenantDomainDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantDomainDetailResponse:
        """Test TenantDomainDetailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantDomainDetailResponse`
        """
        model = TenantDomainDetailResponse()
        if include_optional:
            return TenantDomainDetailResponse(
                data = openapi_client.models.tenant_domain_detail.TenantDomainDetail(
                    domain = 'yourdomain.com', 
                    mail_from_domain = 'mail.yourdomain.com', 
                    status = 'PENDING', 
                    ses = openapi_client.models.tenant_domain_ses_status.TenantDomainSesStatus(
                        verification_status = 'PENDING', 
                        dkim_status = 'PENDING', ), 
                    records = [
                        openapi_client.models.tenant_domain_record.TenantDomainRecord(
                            type = 'CNAME', 
                            name = 'cieoxyt4oxhvpr5zmdeqxoxzqgs6umsu._domainkey.yourdomain.com', 
                            value = 'cieoxyt4oxhvpr5zmdeqxoxzqgs6umsu.dkim.amazonses.com', )
                        ], )
            )
        else:
            return TenantDomainDetailResponse(
                data = openapi_client.models.tenant_domain_detail.TenantDomainDetail(
                    domain = 'yourdomain.com', 
                    mail_from_domain = 'mail.yourdomain.com', 
                    status = 'PENDING', 
                    ses = openapi_client.models.tenant_domain_ses_status.TenantDomainSesStatus(
                        verification_status = 'PENDING', 
                        dkim_status = 'PENDING', ), 
                    records = [
                        openapi_client.models.tenant_domain_record.TenantDomainRecord(
                            type = 'CNAME', 
                            name = 'cieoxyt4oxhvpr5zmdeqxoxzqgs6umsu._domainkey.yourdomain.com', 
                            value = 'cieoxyt4oxhvpr5zmdeqxoxzqgs6umsu.dkim.amazonses.com', )
                        ], ),
        )
        """

    def testTenantDomainDetailResponse(self):
        """Test TenantDomainDetailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
