# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.tenant_message import TenantMessage

class TestTenantMessage(unittest.TestCase):
    """TenantMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantMessage:
        """Test TenantMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantMessage`
        """
        model = TenantMessage()
        if include_optional:
            return TenantMessage(
                tenant_id = 'af57c621-e979-4a8b-8415-7fdb7a07982c',
                request_id = '1a011c24-788e-4273-8c81-fd7d767bf0c0',
                status = 'ACCEPTED',
                reason = '',
                created_at = 1773398594,
                updated_at = 1773398596,
                last_event_at = 1773398596,
                created_at_iso = '2026-03-13T10:43:14.338Z',
                updated_at_iso = '2026-03-13T10:43:16.519Z',
                last_event_at_iso = '2026-03-13T10:43:16.269Z',
                to = 'developers@dependal.com',
                var_from = 'Dependal <noreply@dependal.com>',
                subject = 'Dependal test send',
                source_ip = '90.201.28.251',
                stage = 'dev',
                tag = '',
                key_id = 'ak-ez8lrxnZCi',
                caller_type = 'public',
                last_source = 'api',
                last_event_type = 'ACCEPTED',
                ses_message_id = '010b019ce6cb1552-32720d7c-a2cd-4716-a559-f587669ecacb-000000',
                idempotency_key = '735c4c4f94e1d23e8c9686c5d92e52bcb19f3e91e02ddc42ee4387a6270a1907',
                metadata = { },
                meta = openapi_client.models.tenant_message_meta.TenantMessageMeta(
                    delivery = openapi_client.models.tenant_message_meta_delivery.TenantMessageMetaDelivery(
                        processing_time_millis = 1371, ), )
            )
        else:
            return TenantMessage(
                tenant_id = 'af57c621-e979-4a8b-8415-7fdb7a07982c',
                request_id = '1a011c24-788e-4273-8c81-fd7d767bf0c0',
                status = 'ACCEPTED',
                reason = '',
                created_at = 1773398594,
                updated_at = 1773398596,
                last_event_at = 1773398596,
                created_at_iso = '2026-03-13T10:43:14.338Z',
                updated_at_iso = '2026-03-13T10:43:16.519Z',
                last_event_at_iso = '2026-03-13T10:43:16.269Z',
                to = 'developers@dependal.com',
                var_from = 'Dependal <noreply@dependal.com>',
                subject = 'Dependal test send',
                source_ip = '90.201.28.251',
                stage = 'dev',
                tag = '',
                key_id = 'ak-ez8lrxnZCi',
                caller_type = 'public',
                last_source = 'api',
                last_event_type = 'ACCEPTED',
                ses_message_id = '010b019ce6cb1552-32720d7c-a2cd-4716-a559-f587669ecacb-000000',
                idempotency_key = '735c4c4f94e1d23e8c9686c5d92e52bcb19f3e91e02ddc42ee4387a6270a1907',
                metadata = { },
                meta = openapi_client.models.tenant_message_meta.TenantMessageMeta(
                    delivery = openapi_client.models.tenant_message_meta_delivery.TenantMessageMetaDelivery(
                        processing_time_millis = 1371, ), ),
        )
        """

    def testTenantMessage(self):
        """Test TenantMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
