# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.tenant_message_event_common_headers import TenantMessageEventCommonHeaders

class TestTenantMessageEventCommonHeaders(unittest.TestCase):
    """TenantMessageEventCommonHeaders unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantMessageEventCommonHeaders:
        """Test TenantMessageEventCommonHeaders
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantMessageEventCommonHeaders`
        """
        model = TenantMessageEventCommonHeaders()
        if include_optional:
            return TenantMessageEventCommonHeaders(
                message_id = '010b019ce6cb1552-32720d7c-a2cd-4716-a559-f587669ecacb-000000',
                var_from = [Dependal <noreply@dependal.com>],
                to = [developers@dependal.com],
                subject = 'Dependal test send'
            )
        else:
            return TenantMessageEventCommonHeaders(
                message_id = '010b019ce6cb1552-32720d7c-a2cd-4716-a559-f587669ecacb-000000',
                var_from = [Dependal <noreply@dependal.com>],
                to = [developers@dependal.com],
                subject = 'Dependal test send',
        )
        """

    def testTenantMessageEventCommonHeaders(self):
        """Test TenantMessageEventCommonHeaders"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
