# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.tenant_message_internal_event import TenantMessageInternalEvent

class TestTenantMessageInternalEvent(unittest.TestCase):
    """TenantMessageInternalEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantMessageInternalEvent:
        """Test TenantMessageInternalEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantMessageInternalEvent`
        """
        model = TenantMessageInternalEvent()
        if include_optional:
            return TenantMessageInternalEvent(
                stage = 'dev',
                detail = {},
                tenant_id = 'af57c621-e979-4a8b-8415-7fdb7a07982c',
                caller_type = 'public',
                status = 'ACCEPTED',
                source = 'api',
                created_at_iso = '2026-03-13T10:43:15.038Z',
                reason = '',
                request_id = '1a011c24-788e-4273-8c81-fd7d767bf0c0',
                event_at_iso = '2026-03-13T10:43:15.038Z',
                event_type = 'provider.accepted',
                tag = '',
                event_group = 'internal'
            )
        else:
            return TenantMessageInternalEvent(
                stage = 'dev',
                detail = {},
                tenant_id = 'af57c621-e979-4a8b-8415-7fdb7a07982c',
                caller_type = 'public',
                status = 'ACCEPTED',
                source = 'api',
                created_at_iso = '2026-03-13T10:43:15.038Z',
                reason = '',
                request_id = '1a011c24-788e-4273-8c81-fd7d767bf0c0',
                event_at_iso = '2026-03-13T10:43:15.038Z',
                event_type = 'provider.accepted',
                tag = '',
                event_group = 'internal',
        )
        """

    def testTenantMessageInternalEvent(self):
        """Test TenantMessageInternalEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
