# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.tenant_domain_create import TenantDomainCreate

class TestTenantDomainCreate(unittest.TestCase):
    """TenantDomainCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantDomainCreate:
        """Test TenantDomainCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantDomainCreate`
        """
        model = TenantDomainCreate()
        if include_optional:
            return TenantDomainCreate(
                domain = 'yourdomain.com',
                status = 'PENDING'
            )
        else:
            return TenantDomainCreate(
                domain = 'yourdomain.com',
                status = 'PENDING',
        )
        """

    def testTenantDomainCreate(self):
        """Test TenantDomainCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
