# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.api.tenant_api import TenantApi


class TestTenantApi(unittest.TestCase):
    """TenantApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TenantApi()

    def tearDown(self) -> None:
        pass

    def test_accept_tenant_policies(self) -> None:
        """Test case for accept_tenant_policies

        Accept tenant policies
        """
        pass


if __name__ == '__main__':
    unittest.main()
