# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.tenant_domains_response import TenantDomainsResponse

class TestTenantDomainsResponse(unittest.TestCase):
    """TenantDomainsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantDomainsResponse:
        """Test TenantDomainsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantDomainsResponse`
        """
        model = TenantDomainsResponse()
        if include_optional:
            return TenantDomainsResponse(
                data = [
                    openapi_client.models.tenant_domain.TenantDomain(
                        domain = 'example.com', 
                        status = 'PENDING', 
                        created_at = 1773329146, 
                        verified_at = 56, 
                        updated_at = '2026-03-12T15:25:46.312Z', )
                    ]
            )
        else:
            return TenantDomainsResponse(
                data = [
                    openapi_client.models.tenant_domain.TenantDomain(
                        domain = 'example.com', 
                        status = 'PENDING', 
                        created_at = 1773329146, 
                        verified_at = 56, 
                        updated_at = '2026-03-12T15:25:46.312Z', )
                    ],
        )
        """

    def testTenantDomainsResponse(self):
        """Test TenantDomainsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
