# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.domain_status_enum import DomainStatusEnum

class TestDomainStatusEnum(unittest.TestCase):
    """DomainStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainStatusEnum(self):
        """Test DomainStatusEnum"""
        # inst = DomainStatusEnum()

if __name__ == '__main__':
    unittest.main()
