# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.tenant_message_event_mail import TenantMessageEventMail

class TestTenantMessageEventMail(unittest.TestCase):
    """TenantMessageEventMail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantMessageEventMail:
        """Test TenantMessageEventMail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantMessageEventMail`
        """
        model = TenantMessageEventMail()
        if include_optional:
            return TenantMessageEventMail(
                source_arn = 'arn:aws:ses:eu-west-2:154673467564:identity/dependal.com',
                headers = [
                    openapi_client.models.tenant_message_event_header.TenantMessageEventHeader(
                        name = 'From', 
                        value = 'Dependal <noreply@dependal.com>', )
                    ],
                sending_account_id = '154673467564',
                destination = [developers@dependal.com],
                headers_truncated = False,
                message_id = '010b019ce6cb1552-32720d7c-a2cd-4716-a559-f587669ecacb-000000',
                source = '"Dependal" <noreply@dependal.com>',
                timestamp = '2026-03-13T10:43:14.898Z',
                common_headers = openapi_client.models.tenant_message_event_common_headers.TenantMessageEventCommonHeaders(
                    message_id = '010b019ce6cb1552-32720d7c-a2cd-4716-a559-f587669ecacb-000000', 
                    from = [Dependal <noreply@dependal.com>], 
                    to = [developers@dependal.com], 
                    subject = 'Dependal test send', ),
                tags = {
                    'key' : [
                        ''
                        ]
                    }
            )
        else:
            return TenantMessageEventMail(
        )
        """

    def testTenantMessageEventMail(self):
        """Test TenantMessageEventMail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
