# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.tenant_message_event import TenantMessageEvent

class TestTenantMessageEvent(unittest.TestCase):
    """TenantMessageEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantMessageEvent:
        """Test TenantMessageEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantMessageEvent`
        """
        model = TenantMessageEvent()
        if include_optional:
            return TenantMessageEvent(
                event_at_iso = '2026-03-13T10:43:15.038Z',
                recipient = 'developers@dependal.com',
                provider_message_id = '010b019ce6cb1552-32720d7c-a2cd-4716-a559-f587669ecacb-000000',
                message_id = '1a011c24-788e-4273-8c81-fd7d767bf0c0',
                meta = {
                    'key' : null
                    },
                tenant_id = 'af57c621-e979-4a8b-8415-7fdb7a07982c',
                event_at = 1773398596,
                provider = 'SES',
                event_type = 'provider.accepted',
                event_group = 'internal',
                stage = 'dev',
                detail = {},
                caller_type = 'public',
                status = 'ACCEPTED',
                source = 'api',
                created_at_iso = '2026-03-13T10:43:15.038Z',
                reason = '',
                request_id = '1a011c24-788e-4273-8c81-fd7d767bf0c0',
                tag = ''
            )
        else:
            return TenantMessageEvent(
                event_at_iso = '2026-03-13T10:43:15.038Z',
                recipient = 'developers@dependal.com',
                provider_message_id = '010b019ce6cb1552-32720d7c-a2cd-4716-a559-f587669ecacb-000000',
                message_id = '1a011c24-788e-4273-8c81-fd7d767bf0c0',
                meta = {
                    'key' : null
                    },
                tenant_id = 'af57c621-e979-4a8b-8415-7fdb7a07982c',
                event_at = 1773398596,
                provider = 'SES',
                event_type = 'provider.accepted',
                event_group = 'internal',
                stage = 'dev',
                detail = {},
                caller_type = 'public',
                status = 'ACCEPTED',
                source = 'api',
                created_at_iso = '2026-03-13T10:43:15.038Z',
                reason = '',
                request_id = '1a011c24-788e-4273-8c81-fd7d767bf0c0',
                tag = '',
        )
        """

    def testTenantMessageEvent(self):
        """Test TenantMessageEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
