# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.send_email_response import SendEmailResponse

class TestSendEmailResponse(unittest.TestCase):
    """SendEmailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendEmailResponse:
        """Test SendEmailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendEmailResponse`
        """
        model = SendEmailResponse()
        if include_optional:
            return SendEmailResponse(
                data = openapi_client.models.send_email_result.SendEmailResult(
                    message_id = '1a011c24-788e-4273-8c81-fd7d767bf0c0', 
                    status = 'ACCEPTED', )
            )
        else:
            return SendEmailResponse(
                data = openapi_client.models.send_email_result.SendEmailResult(
                    message_id = '1a011c24-788e-4273-8c81-fd7d767bf0c0', 
                    status = 'ACCEPTED', ),
        )
        """

    def testSendEmailResponse(self):
        """Test SendEmailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
