# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.send_email_request import SendEmailRequest

class TestSendEmailRequest(unittest.TestCase):
    """SendEmailRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendEmailRequest:
        """Test SendEmailRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendEmailRequest`
        """
        model = SendEmailRequest()
        if include_optional:
            return SendEmailRequest(
                var_from = 'Dependal <noreply@dependal.com>',
                to = 'user@example.com',
                subject = 'Welcome to Dependal',
                text = 'Thanks for signing up.',
                html = '<p>Thanks for signing up.</p>',
                tags = {
                    'key' : ''
                    }
            )
        else:
            return SendEmailRequest(
                var_from = 'Dependal <noreply@dependal.com>',
                to = 'user@example.com',
                subject = 'Welcome to Dependal',
        )
        """

    def testSendEmailRequest(self):
        """Test SendEmailRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
