# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.api.messages_api import MessagesApi


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessagesApi()

    def tearDown(self) -> None:
        pass

    def test_get_message_status(self) -> None:
        """Test case for get_message_status

        Get message delivery status
        """
        pass

    def test_get_tenant_message(self) -> None:
        """Test case for get_tenant_message

        Get tenant message
        """
        pass

    def test_list_tenant_message_events(self) -> None:
        """Test case for list_tenant_message_events

        List tenant message events
        """
        pass

    def test_list_tenant_messages(self) -> None:
        """Test case for list_tenant_messages

        List tenant messages
        """
        pass

    def test_send_email(self) -> None:
        """Test case for send_email

        Send an email
        """
        pass


if __name__ == '__main__':
    unittest.main()
