# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dependal.models.tenant_domain_create_response import TenantDomainCreateResponse

class TestTenantDomainCreateResponse(unittest.TestCase):
    """TenantDomainCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantDomainCreateResponse:
        """Test TenantDomainCreateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantDomainCreateResponse`
        """
        model = TenantDomainCreateResponse()
        if include_optional:
            return TenantDomainCreateResponse(
                data = openapi_client.models.tenant_domain_create.TenantDomainCreate(
                    domain = 'yourdomain.com', 
                    status = 'PENDING', )
            )
        else:
            return TenantDomainCreateResponse(
                data = openapi_client.models.tenant_domain_create.TenantDomainCreate(
                    domain = 'yourdomain.com', 
                    status = 'PENDING', ),
        )
        """

    def testTenantDomainCreateResponse(self):
        """Test TenantDomainCreateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
