"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "openapi-client"
VERSION = "1.0.2"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Dependal API",
    author="Dependal Support",
    author_email="support@dependal.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Dependal API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Dependal transactional email API.  Response envelope standard: - Success: &#x60;{ \&quot;data\&quot;: ... }&#x60; - Error: &#x60;{ \&quot;error\&quot;: { \&quot;code\&quot;: \&quot;...\&quot;, \&quot;message\&quot;: \&quot;...\&quot; } }&#x60; 
    """,  # noqa: E501
    package_data={"openapi_client": ["py.typed"]},
)
