# coding: utf-8

# flake8: noqa

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DomainsApi",
    "MessagesApi",
    "TenantApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CallerTypeEnum",
    "DnsRecordTypeEnum",
    "DomainStatusEnum",
    "ErrorBody",
    "ErrorCode",
    "ErrorResponse",
    "EventGroupEnum",
    "MessageStatus",
    "MessageStatusEnum",
    "MessageStatusResponse",
    "ProviderEnum",
    "ProviderEventTypeEnum",
    "SendEmailRequest",
    "SendEmailResponse",
    "SendEmailResult",
    "SesVerificationStatusEnum",
    "SourceEnum",
    "StageEnum",
    "TenantDomain",
    "TenantDomainCheck",
    "TenantDomainCheckResponse",
    "TenantDomainCreate",
    "TenantDomainCreateRequest",
    "TenantDomainCreateResponse",
    "TenantDomainDetail",
    "TenantDomainDetailResponse",
    "TenantDomainRecord",
    "TenantDomainSesStatus",
    "TenantDomainsResponse",
    "TenantMessage",
    "TenantMessageEvent",
    "TenantMessageEventCommonHeaders",
    "TenantMessageEventDelivery",
    "TenantMessageEventHeader",
    "TenantMessageEventMail",
    "TenantMessageEventsPage",
    "TenantMessageEventsResponse",
    "TenantMessageInternalEvent",
    "TenantMessageMeta",
    "TenantMessageMetaDelivery",
    "TenantMessageProviderEvent",
    "TenantMessageProviderMeta",
    "TenantMessageResponse",
    "TenantMessagesPage",
    "TenantMessagesResponse",
    "TenantPoliciesAccept",
    "TenantPoliciesAcceptResponse",
]

# import apis into sdk package
from dependal.api.domains_api import DomainsApi as DomainsApi
from dependal.api.messages_api import MessagesApi as MessagesApi
from dependal.api.tenant_api import TenantApi as TenantApi

# import ApiClient
from dependal.api_response import ApiResponse as ApiResponse
from dependal.api_client import ApiClient as ApiClient
from dependal.configuration import Configuration as Configuration
from dependal.exceptions import OpenApiException as OpenApiException
from dependal.exceptions import ApiTypeError as ApiTypeError
from dependal.exceptions import ApiValueError as ApiValueError
from dependal.exceptions import ApiKeyError as ApiKeyError
from dependal.exceptions import ApiAttributeError as ApiAttributeError
from dependal.exceptions import ApiException as ApiException

# import models into sdk package
from dependal.models.caller_type_enum import CallerTypeEnum as CallerTypeEnum
from dependal.models.dns_record_type_enum import DnsRecordTypeEnum as DnsRecordTypeEnum
from dependal.models.domain_status_enum import DomainStatusEnum as DomainStatusEnum
from dependal.models.error_body import ErrorBody as ErrorBody
from dependal.models.error_code import ErrorCode as ErrorCode
from dependal.models.error_response import ErrorResponse as ErrorResponse
from dependal.models.event_group_enum import EventGroupEnum as EventGroupEnum
from dependal.models.message_status import MessageStatus as MessageStatus
from dependal.models.message_status_enum import MessageStatusEnum as MessageStatusEnum
from dependal.models.message_status_response import MessageStatusResponse as MessageStatusResponse
from dependal.models.provider_enum import ProviderEnum as ProviderEnum
from dependal.models.provider_event_type_enum import ProviderEventTypeEnum as ProviderEventTypeEnum
from dependal.models.send_email_request import SendEmailRequest as SendEmailRequest
from dependal.models.send_email_response import SendEmailResponse as SendEmailResponse
from dependal.models.send_email_result import SendEmailResult as SendEmailResult
from dependal.models.ses_verification_status_enum import SesVerificationStatusEnum as SesVerificationStatusEnum
from dependal.models.source_enum import SourceEnum as SourceEnum
from dependal.models.stage_enum import StageEnum as StageEnum
from dependal.models.tenant_domain import TenantDomain as TenantDomain
from dependal.models.tenant_domain_check import TenantDomainCheck as TenantDomainCheck
from dependal.models.tenant_domain_check_response import TenantDomainCheckResponse as TenantDomainCheckResponse
from dependal.models.tenant_domain_create import TenantDomainCreate as TenantDomainCreate
from dependal.models.tenant_domain_create_request import TenantDomainCreateRequest as TenantDomainCreateRequest
from dependal.models.tenant_domain_create_response import TenantDomainCreateResponse as TenantDomainCreateResponse
from dependal.models.tenant_domain_detail import TenantDomainDetail as TenantDomainDetail
from dependal.models.tenant_domain_detail_response import TenantDomainDetailResponse as TenantDomainDetailResponse
from dependal.models.tenant_domain_record import TenantDomainRecord as TenantDomainRecord
from dependal.models.tenant_domain_ses_status import TenantDomainSesStatus as TenantDomainSesStatus
from dependal.models.tenant_domains_response import TenantDomainsResponse as TenantDomainsResponse
from dependal.models.tenant_message import TenantMessage as TenantMessage
from dependal.models.tenant_message_event import TenantMessageEvent as TenantMessageEvent
from dependal.models.tenant_message_event_common_headers import TenantMessageEventCommonHeaders as TenantMessageEventCommonHeaders
from dependal.models.tenant_message_event_delivery import TenantMessageEventDelivery as TenantMessageEventDelivery
from dependal.models.tenant_message_event_header import TenantMessageEventHeader as TenantMessageEventHeader
from dependal.models.tenant_message_event_mail import TenantMessageEventMail as TenantMessageEventMail
from dependal.models.tenant_message_events_page import TenantMessageEventsPage as TenantMessageEventsPage
from dependal.models.tenant_message_events_response import TenantMessageEventsResponse as TenantMessageEventsResponse
from dependal.models.tenant_message_internal_event import TenantMessageInternalEvent as TenantMessageInternalEvent
from dependal.models.tenant_message_meta import TenantMessageMeta as TenantMessageMeta
from dependal.models.tenant_message_meta_delivery import TenantMessageMetaDelivery as TenantMessageMetaDelivery
from dependal.models.tenant_message_provider_event import TenantMessageProviderEvent as TenantMessageProviderEvent
from dependal.models.tenant_message_provider_meta import TenantMessageProviderMeta as TenantMessageProviderMeta
from dependal.models.tenant_message_response import TenantMessageResponse as TenantMessageResponse
from dependal.models.tenant_messages_page import TenantMessagesPage as TenantMessagesPage
from dependal.models.tenant_messages_response import TenantMessagesResponse as TenantMessagesResponse
from dependal.models.tenant_policies_accept import TenantPoliciesAccept as TenantPoliciesAccept
from dependal.models.tenant_policies_accept_response import TenantPoliciesAcceptResponse as TenantPoliciesAcceptResponse

