# coding: utf-8

# flake8: noqa
"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from dependal.models.caller_type_enum import CallerTypeEnum
from dependal.models.dns_record_type_enum import DnsRecordTypeEnum
from dependal.models.domain_status_enum import DomainStatusEnum
from dependal.models.error_body import ErrorBody
from dependal.models.error_code import ErrorCode
from dependal.models.error_response import ErrorResponse
from dependal.models.event_group_enum import EventGroupEnum
from dependal.models.message_status import MessageStatus
from dependal.models.message_status_enum import MessageStatusEnum
from dependal.models.message_status_response import MessageStatusResponse
from dependal.models.provider_enum import ProviderEnum
from dependal.models.provider_event_type_enum import ProviderEventTypeEnum
from dependal.models.send_email_request import SendEmailRequest
from dependal.models.send_email_response import SendEmailResponse
from dependal.models.send_email_result import SendEmailResult
from dependal.models.ses_verification_status_enum import SesVerificationStatusEnum
from dependal.models.source_enum import SourceEnum
from dependal.models.stage_enum import StageEnum
from dependal.models.tenant_domain import TenantDomain
from dependal.models.tenant_domain_check import TenantDomainCheck
from dependal.models.tenant_domain_check_response import TenantDomainCheckResponse
from dependal.models.tenant_domain_create import TenantDomainCreate
from dependal.models.tenant_domain_create_request import TenantDomainCreateRequest
from dependal.models.tenant_domain_create_response import TenantDomainCreateResponse
from dependal.models.tenant_domain_detail import TenantDomainDetail
from dependal.models.tenant_domain_detail_response import TenantDomainDetailResponse
from dependal.models.tenant_domain_record import TenantDomainRecord
from dependal.models.tenant_domain_ses_status import TenantDomainSesStatus
from dependal.models.tenant_domains_response import TenantDomainsResponse
from dependal.models.tenant_message import TenantMessage
from dependal.models.tenant_message_event import TenantMessageEvent
from dependal.models.tenant_message_event_common_headers import TenantMessageEventCommonHeaders
from dependal.models.tenant_message_event_delivery import TenantMessageEventDelivery
from dependal.models.tenant_message_event_header import TenantMessageEventHeader
from dependal.models.tenant_message_event_mail import TenantMessageEventMail
from dependal.models.tenant_message_events_page import TenantMessageEventsPage
from dependal.models.tenant_message_events_response import TenantMessageEventsResponse
from dependal.models.tenant_message_internal_event import TenantMessageInternalEvent
from dependal.models.tenant_message_meta import TenantMessageMeta
from dependal.models.tenant_message_meta_delivery import TenantMessageMetaDelivery
from dependal.models.tenant_message_provider_event import TenantMessageProviderEvent
from dependal.models.tenant_message_provider_meta import TenantMessageProviderMeta
from dependal.models.tenant_message_response import TenantMessageResponse
from dependal.models.tenant_messages_page import TenantMessagesPage
from dependal.models.tenant_messages_response import TenantMessagesResponse
from dependal.models.tenant_policies_accept import TenantPoliciesAccept
from dependal.models.tenant_policies_accept_response import TenantPoliciesAcceptResponse

