# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CallerTypeEnum(str, Enum):
    """
    CallerTypeEnum
    """

    """
    allowed enum values
    """
    PUBLIC = 'public'
    SMTP = 'smtp'
    ADMIN = 'admin'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CallerTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


