# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ErrorCode(str, Enum):
    """
    ErrorCode
    """

    """
    allowed enum values
    """
    BAD_REQUEST = 'BAD_REQUEST'
    UNAUTHORIZED = 'UNAUTHORIZED'
    FORBIDDEN = 'FORBIDDEN'
    NOT_FOUND = 'NOT_FOUND'
    VALIDATION_ERROR = 'VALIDATION_ERROR'
    CONFLICT = 'CONFLICT'
    PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE'
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
    DOMAIN_NOT_VERIFIED = 'DOMAIN_NOT_VERIFIED'
    SENDING_NOT_ENABLED = 'SENDING_NOT_ENABLED'
    POLICY_NOT_ACCEPTED = 'POLICY_NOT_ACCEPTED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ErrorCode from a JSON string"""
        return cls(json.loads(json_str))


