# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from dependal.models.message_status_enum import MessageStatusEnum
from typing import Optional, Set
from typing_extensions import Self

class MessageStatus(BaseModel):
    """
    MessageStatus
    """ # noqa: E501
    message_id: UUID = Field(alias="messageId")
    status: MessageStatusEnum
    reason: Optional[StrictStr] = Field(description="Optional reason for failure, bounce, complaint, or rejection")
    created_at: StrictInt = Field(description="Unix timestamp in seconds", alias="createdAt")
    updated_at: StrictInt = Field(description="Unix timestamp in seconds", alias="updatedAt")
    to: StrictStr
    var_from: StrictStr = Field(alias="from")
    subject: StrictStr
    sending_message_id: Optional[StrictStr] = Field(description="Provider message identifier", alias="sendingMessageId")
    __properties: ClassVar[List[str]] = ["messageId", "status", "reason", "createdAt", "updatedAt", "to", "from", "subject", "sendingMessageId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MessageStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        # set to None if sending_message_id (nullable) is None
        # and model_fields_set contains the field
        if self.sending_message_id is None and "sending_message_id" in self.model_fields_set:
            _dict['sendingMessageId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MessageStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "messageId": obj.get("messageId"),
            "status": obj.get("status"),
            "reason": obj.get("reason"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "to": obj.get("to"),
            "from": obj.get("from"),
            "subject": obj.get("subject"),
            "sendingMessageId": obj.get("sendingMessageId")
        })
        return _obj


