# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ProviderEventTypeEnum(str, Enum):
    """
    ProviderEventTypeEnum
    """

    """
    allowed enum values
    """
    SEND = 'Send'
    DELIVERY = 'Delivery'
    BOUNCE = 'Bounce'
    COMPLAINT = 'Complaint'
    OPEN = 'Open'
    CLICK = 'Click'
    REJECT = 'Reject'
    RENDERINGFAILURE = 'RenderingFailure'
    DELIVERYDELAY = 'DeliveryDelay'
    SUBSCRIPTION = 'Subscription'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProviderEventTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


