# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dependal.models.tenant_message_event_common_headers import TenantMessageEventCommonHeaders
from dependal.models.tenant_message_event_header import TenantMessageEventHeader
from typing import Optional, Set
from typing_extensions import Self

class TenantMessageEventMail(BaseModel):
    """
    TenantMessageEventMail
    """ # noqa: E501
    source_arn: Optional[StrictStr] = Field(default=None, alias="sourceArn")
    headers: Optional[List[TenantMessageEventHeader]] = None
    sending_account_id: Optional[StrictStr] = Field(default=None, alias="sendingAccountId")
    destination: Optional[List[StrictStr]] = None
    headers_truncated: Optional[StrictBool] = Field(default=None, alias="headersTruncated")
    message_id: Optional[StrictStr] = Field(default=None, alias="messageId")
    source: Optional[StrictStr] = None
    timestamp: Optional[datetime] = None
    common_headers: Optional[TenantMessageEventCommonHeaders] = Field(default=None, alias="commonHeaders")
    tags: Optional[Dict[str, List[StrictStr]]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["sourceArn", "headers", "sendingAccountId", "destination", "headersTruncated", "messageId", "source", "timestamp", "commonHeaders", "tags"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TenantMessageEventMail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in headers (list)
        _items = []
        if self.headers:
            for _item_headers in self.headers:
                if _item_headers:
                    _items.append(_item_headers.to_dict())
            _dict['headers'] = _items
        # override the default output from pydantic by calling `to_dict()` of common_headers
        if self.common_headers:
            _dict['commonHeaders'] = self.common_headers.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TenantMessageEventMail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sourceArn": obj.get("sourceArn"),
            "headers": [TenantMessageEventHeader.from_dict(_item) for _item in obj["headers"]] if obj.get("headers") is not None else None,
            "sendingAccountId": obj.get("sendingAccountId"),
            "destination": obj.get("destination"),
            "headersTruncated": obj.get("headersTruncated"),
            "messageId": obj.get("messageId"),
            "source": obj.get("source"),
            "timestamp": obj.get("timestamp"),
            "commonHeaders": TenantMessageEventCommonHeaders.from_dict(obj["commonHeaders"]) if obj.get("commonHeaders") is not None else None,
            "tags": obj.get("tags")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


