# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from dependal.models.caller_type_enum import CallerTypeEnum
from dependal.models.message_status_enum import MessageStatusEnum
from dependal.models.source_enum import SourceEnum
from dependal.models.stage_enum import StageEnum
from dependal.models.tenant_message_meta import TenantMessageMeta
from typing import Optional, Set
from typing_extensions import Self

class TenantMessage(BaseModel):
    """
    TenantMessage
    """ # noqa: E501
    tenant_id: UUID = Field(alias="tenantId")
    request_id: UUID = Field(alias="requestId")
    status: MessageStatusEnum
    reason: Optional[StrictStr]
    created_at: StrictInt = Field(description="Unix timestamp in seconds", alias="createdAt")
    updated_at: StrictInt = Field(description="Unix timestamp in seconds", alias="updatedAt")
    last_event_at: Optional[StrictInt] = Field(description="Unix timestamp in seconds of the latest known event", alias="lastEventAt")
    created_at_iso: datetime = Field(alias="createdAtIso")
    updated_at_iso: datetime = Field(alias="updatedAtIso")
    last_event_at_iso: Optional[datetime] = Field(alias="lastEventAtIso")
    to: StrictStr
    var_from: StrictStr = Field(alias="from")
    subject: StrictStr
    source_ip: Optional[StrictStr] = Field(alias="sourceIp")
    stage: Optional[StageEnum]
    tag: Optional[StrictStr]
    key_id: Optional[StrictStr] = Field(alias="keyId")
    caller_type: CallerTypeEnum = Field(alias="callerType")
    last_source: Optional[SourceEnum] = Field(alias="lastSource")
    last_event_type: Optional[MessageStatusEnum] = Field(alias="lastEventType")
    ses_message_id: Optional[StrictStr] = Field(alias="sesMessageId")
    idempotency_key: Optional[StrictStr] = Field(alias="idempotencyKey")
    metadata: Optional[Dict[str, Any]]
    meta: Optional[TenantMessageMeta]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["tenantId", "requestId", "status", "reason", "createdAt", "updatedAt", "lastEventAt", "createdAtIso", "updatedAtIso", "lastEventAtIso", "to", "from", "subject", "sourceIp", "stage", "tag", "keyId", "callerType", "lastSource", "lastEventType", "sesMessageId", "idempotencyKey", "metadata", "meta"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TenantMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        # set to None if last_event_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_event_at is None and "last_event_at" in self.model_fields_set:
            _dict['lastEventAt'] = None

        # set to None if last_event_at_iso (nullable) is None
        # and model_fields_set contains the field
        if self.last_event_at_iso is None and "last_event_at_iso" in self.model_fields_set:
            _dict['lastEventAtIso'] = None

        # set to None if source_ip (nullable) is None
        # and model_fields_set contains the field
        if self.source_ip is None and "source_ip" in self.model_fields_set:
            _dict['sourceIp'] = None

        # set to None if stage (nullable) is None
        # and model_fields_set contains the field
        if self.stage is None and "stage" in self.model_fields_set:
            _dict['stage'] = None

        # set to None if tag (nullable) is None
        # and model_fields_set contains the field
        if self.tag is None and "tag" in self.model_fields_set:
            _dict['tag'] = None

        # set to None if key_id (nullable) is None
        # and model_fields_set contains the field
        if self.key_id is None and "key_id" in self.model_fields_set:
            _dict['keyId'] = None

        # set to None if last_source (nullable) is None
        # and model_fields_set contains the field
        if self.last_source is None and "last_source" in self.model_fields_set:
            _dict['lastSource'] = None

        # set to None if last_event_type (nullable) is None
        # and model_fields_set contains the field
        if self.last_event_type is None and "last_event_type" in self.model_fields_set:
            _dict['lastEventType'] = None

        # set to None if ses_message_id (nullable) is None
        # and model_fields_set contains the field
        if self.ses_message_id is None and "ses_message_id" in self.model_fields_set:
            _dict['sesMessageId'] = None

        # set to None if idempotency_key (nullable) is None
        # and model_fields_set contains the field
        if self.idempotency_key is None and "idempotency_key" in self.model_fields_set:
            _dict['idempotencyKey'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if meta (nullable) is None
        # and model_fields_set contains the field
        if self.meta is None and "meta" in self.model_fields_set:
            _dict['meta'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TenantMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenantId": obj.get("tenantId"),
            "requestId": obj.get("requestId"),
            "status": obj.get("status"),
            "reason": obj.get("reason"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "lastEventAt": obj.get("lastEventAt"),
            "createdAtIso": obj.get("createdAtIso"),
            "updatedAtIso": obj.get("updatedAtIso"),
            "lastEventAtIso": obj.get("lastEventAtIso"),
            "to": obj.get("to"),
            "from": obj.get("from"),
            "subject": obj.get("subject"),
            "sourceIp": obj.get("sourceIp"),
            "stage": obj.get("stage"),
            "tag": obj.get("tag"),
            "keyId": obj.get("keyId"),
            "callerType": obj.get("callerType"),
            "lastSource": obj.get("lastSource"),
            "lastEventType": obj.get("lastEventType"),
            "sesMessageId": obj.get("sesMessageId"),
            "idempotencyKey": obj.get("idempotencyKey"),
            "metadata": obj.get("metadata"),
            "meta": TenantMessageMeta.from_dict(obj["meta"]) if obj.get("meta") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


