# coding: utf-8

"""
    Dependal API

    Dependal transactional email API.  Response envelope standard: - Success: `{ \"data\": ... }` - Error: `{ \"error\": { \"code\": \"...\", \"message\": \"...\" } }` 

    The version of the OpenAPI document: 1.0.0
    Contact: support@dependal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from dependal.models.event_group_enum import EventGroupEnum
from dependal.models.message_status_enum import MessageStatusEnum
from dependal.models.provider_enum import ProviderEnum
from dependal.models.tenant_message_provider_meta import TenantMessageProviderMeta
from typing import Optional, Set
from typing_extensions import Self

class TenantMessageProviderEvent(BaseModel):
    """
    TenantMessageProviderEvent
    """ # noqa: E501
    event_at_iso: datetime = Field(alias="eventAtIso")
    recipient: StrictStr
    provider_message_id: Optional[StrictStr] = Field(alias="providerMessageId")
    message_id: UUID = Field(alias="messageId")
    meta: TenantMessageProviderMeta
    tenant_id: UUID = Field(alias="tenantId")
    event_at: StrictInt = Field(description="Unix timestamp in seconds", alias="eventAt")
    provider: ProviderEnum
    event_type: MessageStatusEnum = Field(alias="eventType")
    event_group: EventGroupEnum = Field(alias="eventGroup")
    __properties: ClassVar[List[str]] = ["eventAtIso", "recipient", "providerMessageId", "messageId", "meta", "tenantId", "eventAt", "provider", "eventType", "eventGroup"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TenantMessageProviderEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        # set to None if provider_message_id (nullable) is None
        # and model_fields_set contains the field
        if self.provider_message_id is None and "provider_message_id" in self.model_fields_set:
            _dict['providerMessageId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TenantMessageProviderEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "eventAtIso": obj.get("eventAtIso"),
            "recipient": obj.get("recipient"),
            "providerMessageId": obj.get("providerMessageId"),
            "messageId": obj.get("messageId"),
            "meta": TenantMessageProviderMeta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "tenantId": obj.get("tenantId"),
            "eventAt": obj.get("eventAt"),
            "provider": obj.get("provider"),
            "eventType": obj.get("eventType"),
            "eventGroup": obj.get("eventGroup")
        })
        return _obj


